a=15
print(a)
try:
    print(a)
except:
    print("An error occurred while printing a")
else:
    print("No errors occurred while printing a")
finally:
    print("Execution completed")
import functions
import demo
print(functions.add(5,6))
print(functions.sub(16,10))
print(functions.div(16,12))
a=16
try:
    print(b)
except:
    print("An error occurred while printing b")
else:
    print("No errors occurred while printing b")
finally:
    print("Execution completed")